In [12]:
import numpy as np
uniform_data = np.random.uniform(low=0.0, high=1.0, size=10)
uniform_data

array([0.89728401, 0.29721629, 0.15132178, 0.39619791, 0.19908064,
       0.54362625, 0.11889169, 0.2969848 , 0.04202374, 0.9023697 ])

In [13]:
normal_data = np.random.normal(loc=0.0, scale=1.0, size=10)
normal_data

array([ 0.09031836, -0.41355726, -1.37717778, -0.82594632, -0.0416544 ,
        1.21358255,  1.02980077, -0.74458272,  1.41907884,  1.32739291])

In [14]:
binomial_data = np.random.binomial(n=10, p=0.5, size=10)
binomial_data

array([7, 4, 7, 4, 4, 7, 6, 7, 7, 4], dtype=int32)

In [15]:
poisson_data = np.random.poisson(lam=5, size=10)
poisson_data

array([5, 4, 3, 6, 3, 6, 3, 6, 7, 7], dtype=int32)

In [17]:
mean_value = np.mean(normal_data)
mean_value

np.float64(0.16772549452562796)

In [19]:
median_value = np.median(normal_data)
mean_value

np.float64(0.16772549452562796)

In [20]:
variance_value = np.var(normal_data)
variance_value

np.float64(0.9341842005214854)

In [21]:
std_dev_value = np.std(normal_data)
std_dev_value

np.float64(0.9665320483675052)

In [22]:
data = np.random.normal(loc=50, scale=10, size=1000)
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print(f"25th percentile : {percentile_25}\n75th percentile : {percentile_75}")

25th percentile : 43.161859148126254
75th percentile : 56.924068971996974


In [23]:
x = np.random.normal(0, 1, 1000)
y = np.random.normal(0, 1, 1000)
correlation = np.corrcoef(x, y)
covariance_matrix = np.cov(x, y)
print(f"Correlation : {correlation}\nCovariance : {covariance_matrix}")

Correlation : [[ 1.         -0.01173687]
 [-0.01173687  1.        ]]
Covariance : [[ 1.01789257 -0.01158137]
 [-0.01158137  0.95656264]]
