In [2]:
import numpy as np

In [3]:
matrix1 = np.array([[1,3],
                    [5,7]])
matrix1

array([[1, 3],
       [5, 7]])

In [4]:
matrix2 = np.array([[2,3,5],
                    [7,14,21],
                   [1,3,5]])
matrix2

array([[ 2,  3,  5],
       [ 7, 14, 21],
       [ 1,  3,  5]])

In [5]:
A = np.array ([[1,2],[3,4]])
B = np.array ([[4,5],[6,7]])

print("Array A = \n",A)
print("Array B = \n",B)

C = np.add(A,B)
print("A + B = \n",C)

Array A = 
 [[1 2]
 [3 4]]
Array B = 
 [[4 5]
 [6 7]]
A + B = 
 [[ 5  7]
 [ 9 11]]


In [6]:
A = np.array ([[1,3],[5,7]])
B = np.array ([[2,6],[4,8]])

print("Array A = \n",A)
print("Array B = \n",B)

C = np.dot(A, B)
print("A . B = \n",C)

Array A = 
 [[1 3]
 [5 7]]
Array B = 
 [[2 6]
 [4 8]]
A . B = 
 [[14 30]
 [38 86]]


In [7]:
A = np.array ([[1,2],[3,4]])
B = np.array ([[4,5],[6,7]])

print("Array A = \n",A)
print("Array B = \n",B)

C = np.subtract(A,B)
print("A - B = \n",C)

Array A = 
 [[1 2]
 [3 4]]
Array B = 
 [[4 5]
 [6 7]]
A + B = 
 [[-3 -3]
 [-3 -3]]


In [8]:
A = np.array ([[1,3],[5,7]])

print("Array A = \n",A)

C = np.transpose(A)
print("Transpose of A = \n",C)

Array A = 
 [[1 3]
 [5 7]]
Transpose of A = 
 [[1 5]
 [3 7]]


In [9]:
A = np.array([[1,3,5],
             [7,9,2],
             [4,6,8]])

print("Array A = \n",A)

C = np.linalg.inv(A)
print("Inverse of A = \n",C)

Array A = 
 [[1 3 5]
 [7 9 2]
 [4 6 8]]
Inverse of A = 
 [[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]
