In [52]:
import numpy as np

A = np.array([3, 22, 28, 56])
B = np.array([6, 88, 29, 35])

print("Array A = \n",A)
print("Array B = \n",B)

C = A + B

print("A + B = \n",C)

Array A = 
 [ 3 22 28 56]
Array B = 
 [ 6 88 29 35]
A + B = 
 [  9 110  57  91]


In [53]:
D = np.array([67, 68, 69, 70])

print("Array D = \n",D)

E = A + B + D

print("A + B + D = \n",E)

Array D = 
 [67 68 69 70]
A + B + D = 
 [ 76 178 126 161]


In [54]:
F = np.add(A, B, D)

print("A + B + D (using add func) = \n",F)

A + B + D (using add func) = 
 [  9 110  57  91]


In [55]:
A = np.array ([5, 72, 13, 100])
B = np.array ([2, 5, 10, 30])

print("Array A = \n",A)
print("Array B = \n",B)

C = A - B

print("A - B = \n",C)

Array A = 
 [  5  72  13 100]
Array B = 
 [ 2  5 10 30]
A - B = 
 [ 3 67  3 70]


In [56]:
D = A * B

print("A * B = \n",D)

A * B = 
 [  10  360  130 3000]


In [57]:
E = np.multiply(A, B)

print("A * B = \n",E)

A * B = 
 [  10  360  130 3000]


In [58]:
F = A / B

print("A / B = \n",F)

A / B = 
 [ 2.5        14.4         1.3         3.33333333]


In [59]:
G = np.divide(A, B)

print("A / B = \n",G)

A / B = 
 [ 2.5        14.4         1.3         3.33333333]


In [60]:
C = np.mod(A, B)

print("A % B = \n",C)

A % B = 
 [ 1  2  3 10]


In [61]:
D = np.remainder(A, B)

print("A % B = \n",D)

A % B = 
 [ 1  2  3 10]


In [62]:
E = np.power(A, B)

print("A ^ B = \n",E)

A ^ B = 
 [                 25          1934917632        137858491849
 1152921504606846976]


In [63]:
M = np.mean(A)

print("Mean of A = \n",M)

Mean of A = 
 47.5


In [64]:
Av = np.average(B)

print("Average of B = \n",Av)

Average of B = 
 11.75


In [65]:
S = np.sum(A)

print("Sum of Elements of A = \n",S)

Sum of Elements of A = 
 190


In [66]:
V = np.var(B)

print("Variance of B = \n",V)

Variance of B = 
 119.1875


In [67]:
array1 = np.array([1,3,5,7,2,4,6,8])

res = np.reshape(array1, (2,4))
res

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [68]:
res = np.reshape(array1, (4,2))
res

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [69]:
res2 = np.reshape(array1, (1,8))
res2

array([[1, 3, 5, 7, 2, 4, 6, 8]])

In [70]:
res3 = np.reshape(array1, (2,2,2))
res3

array([[[1, 3],
        [5, 7]],

       [[2, 4],
        [6, 8]]])

In [71]:
array2 = np.array([[[1,3],[5,7]],[[2,4],[6,8]]])
print(array2)

res4 = np.reshape(array2, -1)
res4

[[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


array([1, 3, 5, 7, 2, 4, 6, 8])

In [72]:
array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])

print(array1[2:6])
 
print(array1[0:8:2])

print(array1[3:])

print(array1[:])

[5 7 8 9]
[1 5 8 2]
[7 8 9 2 4 6]
[1 3 5 7 8 9 2 4 6]


In [73]:
numbers = np.array([2, 4, 6, 8, 10, 12])

numbers[3:] = 20
print(numbers)

[ 2  4  6 20 20 20]


In [74]:
numbers = np.array([2, 4, 6, 8, 10, 12])

numbers[:3] = 40
print(numbers)

[40 40 40  8 10 12]


In [75]:
numbers = np.array([2, 4, 6, 8, 10, 12])

numbers[2:5] = 22
print(numbers)

[ 2  4 22 22 22 12]


In [76]:
numbers = np.array([2, 4, 6, 8, 10, 12])

numbers[1:5:2] = 16
print(numbers)

[ 2 16  6 16 10 12]


In [77]:
numbers = np.array([2, 4, 6, 8, 10, 12])

print(numbers[-3:])

print(numbers[-5:-2])

print(numbers[-1::-2])

[ 8 10 12]
[4 6 8]
[12  8  4]


In [78]:
numbers = np.array([2, 4, 6, 8, 10, 12])

reversed_numbers = numbers[::-1]
print(reversed_numbers)

[12 10  8  6  4  2]


In [79]:
array1 = np.array([[1, 3, 5, 7], 
                   [9, 11, 13, 15]])

print(array1[:2, :2])

[[ 1  3]
 [ 9 11]]


In [80]:
array1 = np.array([[1, 3, 5, 7], 
                      [9, 11, 13, 15],
                      [2, 4, 6, 8]])

subarray1 = array1[:2, :2]
subarray2 = array1[1:3, 2:4]

print("First Two Rows and Columns: \n",subarray1)
print("Last two Rows and Columns: \n",subarray2)

First Two Rows and Columns: 
 [[ 1  3]
 [ 9 11]]
Last two Rows and Columns: 
 [[13 15]
 [ 6  8]]
